install.packages("plot.matrix")
install.packages("dplyr")
install.packages("janitor")
install.packages("tidyr")
install.packages("poliscidata")
install.packages("gapminder")
install.packages("datasets")
install.packages("dslabs")
